language: node_js
node_js:
- 6
install: npm install
script:
- npm run build
deploy:
  - provider: npm
    edge: true
    email: onap.sdc@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
      repo: onap-sdc/onap-ui-common
